#spring:
#  datasource:
#    url: jdbc:h2:mem:userdatabase;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
#    username: root
#    password: root
#  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#  h2:
#    console:
#      enabled: true



